version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./hello:/db
    environment:
      - USER_EMAIL=test@test.com
      - USER_PASSWORD=password
      - ALLOW_REGISTRATIONS=true
